name: studystream
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  get_storage: ^2.1.1
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  introduction_screen: ^3.1.14
  smooth_page_indicator: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        
  uses-material-design: true

